name: Publish

on:
  push:
    branches:
      - master
    paths:
      - packages/sls-app/src/**
      - packages/sls-app/package.json
      - packages/sls-aws/src/**
      - packages/sls-aws/package.json
      - packages/sls-env/src/**
      - packages/sls-env/package.json
      - .github/workflows/master.yml
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_GITHUB }}

      - name: Configure CI Git User
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'
          scope: '@cabiri'

      - name: get yarn cache
        timeout-minutes: 1
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashfiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: build packages
        run: yarn build

      - name: test
        run: yarn test
        env:
          CI: true

      - name: Updated packages
        run: |
          npx lerna updated

      - name: Version packages
        run: |
          npx lerna version --no-private --create-release github --message "chore(release): publish [skip ci]" --conventional-commits --yes
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}

      - name: Publish packages
        run: npx lerna publish from-git --yes --no-verify-access
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}