name: Publish

on:
  push:
    branches:
      - master
    paths:
      - packages/sls-app/src/**
      - packages/sls-app/package.json
      - packages/sls-aws/src/**
      - packages/sls-aws/package.json
      - packages/sls-env/src/**
      - packages/sls-env/package.json
      - .github/workflows/master.yml
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure CI Git User
        run: |
          git config --global user.email octobot@github.com
          git config --global user.name GitHub Actions

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: get yarn cache
        timeout-minutes: 1
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashfiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: build packages
        run: yarn build
# at the moment it is being release manually
# - name: publish packages
#   run: yarn publish:ci
#   env:
#     CI: true
#     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
